### ISSUE TITLE
Default Parameters for Open Search

### ISSUE THREAD

**Issue by tomthun** [chhh/MSFragger-GUI#45] opened 2018-02-28 12:28 UTC
Hi,

right now i am trying to recreate the results of MSFragger + Philosopher as in the [Paper](https://www.nature.com/articles/nmeth.4256#an1). 
Are the default parameters for open searching in MSFragger-GUI taken from the  [manual of MSFragger](https://media.nature.com/original/nature-assets/nmeth/journal/v14/n5/extref/nmeth.4256-S2.pdf) ? They seem to be pretty much the same.
However i am not sure how to set the parameters for Philosopher according to the paper.

I also wanted to mention that there's a small bug with the report tables: The `psm.tsv` from open search has a typo in the column header. `'Oberved modifications'` is created instead of `'Observed modifications' `
Thanks, 
tom

**Comment by andytyk** [comment] 2018-02-28 18:43
Hi Tom,

The default parameters should be very close to those used in the paper so you should be able to get very similar numbers using the default open search parameters.  There might be some differences due to the bug fixes and changes that have been applied since then.

The default Philosopher settings should provide FDR filtering that is similar to that of the paper.

Best,
Andy

**Comment by tomthun** [comment] 2018-03-01 09:31
Thanks for the answer! The results are similar to the [ones described](https://www.nature.com/articles/nmeth.4256/tables/1). However there are some differences: One of the most puzzling is that there were 122944 peptides discovered in closed search and only 115880 in open search. I expected to find more peptides in open search than in closed. Is this still in the area which can be justified by changes?

**Comment by andytyk** [comment] 2018-03-04 19:46
That's strange, I wouldn't expect to see such large differences.

@prvst Are there changes in Philosopher that can cause this?

**Comment by prvst** [comment] 2018-03-05 22:17
I'm not aware of any changes that could affect values in this way, most changes done in Philosopher so far relate to new functionalities, in overall if the number of filtered peptides is lower than I would assume that the number of PSMs is also lower. Nevertheless, It is natural to expect some differences once that the all software have been evolving since the publication (not trying to explain the difference you see).

**Comment by tomthun** [comment] 2018-03-06 11:27
I also expected some differences but not such large ones. 
Maybe you can start a test-run with the [HEK293 Dataset](http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD001468) and [Human Proteome](http://www.uniprot.org/proteomes/UP000005640) as in the paper? I used the same and it would be interesting if you get the same results as me. 

@andytyk 
This might also be a good dataset for Issue #35 if you take a single Spectrum.

**Comment by anesvi** [comment] 2018-03-07 14:17
MSFragger closed search defaults are not the manuscript defaults. The parameters  used in the manuscript are similar to what Gygi's lab used in their Nature Biotech paper. The 'closed' default parameters in the MSFragger-GUI closed search are not as closed, so to say. Isotope error is allowed, and also several common modifications. There should still be a higher number of PSMs in open search based on all other data sets we recently used. I need to take a look at the MSFragger-GUI settings again.

**Comment by chhh** [comment] 2018-03-08 18:02
@tomthun Looks like there was a regression bug introduced in v2.8.3 that set one default parameter for downstream processing tools incorrectly, which resulted in cutting off a whole lot of identifications in open-searches. We're looking into it.

**Comment by anesvi** [comment] 2018-03-08 21:55
Dear "tomthun" (sorry I do not know your real name),

Thank you very much for bringing up this inconsistency.

Here is what we found. There is no problem with MSFragger or any of the downstream tools. Unfortunately, the default setting for running PeptideProphet for open searches was specified incorrectly in MSFragger-GUI.

At some point ' -' disappeared from the PeptideProphet command in MSFragger-GUI, so '-2' became '2'
The correct command is:
--decoy rev_ --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2

Just to explain what --clevel option does:
CLEVEL is a threshold (measured in the number of standard deviations).
Any PSM with an f-value (which is basically - log (expect))  not higher than CLEVEL standard deviations from the estimated mean f-value of the false PSMs, will automatically be forced to a probability of 0 during modeling. 

The default for this parameter is 0. In open search, the distributions of f-val scores have a certain peculiar property (there are many correct PSMs that are below the mean of the decoy PSM distribution). Thus, we lowered CLEVEL to -2 for open search.

Unfortunately, at some point '-' got lost; So the  default became '2'; this setting was applying a very stringent filter of CLEVEL =2 (instead of the intended -2). Hence, many correct PSMs got filtered by PeptideProphet.

Please rerun your open searches using --clevel -2

We are sorry for this oversight and the inconvenience it may have cased.

For anyone who has run open searches using MSFragger-GUI - I recommend that you rerun your analysis starting with PeptideProphet Tab and use --clevel -2

Now, to get the results that are most close to those in the paper, please use MSFragger settings that we used in the paper. Starting with the default settings, make the following changes:
1. set 'clip N-term' to 0
2. uncheck variable mods: M 15.099 and [^ 42.01  (oxidation and N=term acetyl)
3. set clear m/z range to  0 - 150  
 
4. In addition, for closed search:
change 'Min Matched Frag' to 4  (

5. Add --protProb 0.9 in philosopher filter command (for both open and closed searches)

But you should get better results, for both open and closed searches, with the current defaults  (after you fix that missing '-'2)

Best regards,
Alexey Nesvizhskii, on behalf of the whole team

**Comment by tomthun** [comment] 2018-03-09 14:09
Dear Alexey,

Thank you very much for your in depth explanation of the problem. I changed `--clevel 2` to `--clevel -2` and have overall way better results. When running your suggested settings as in the paper, the results now also lay in the range of the expected.  Thanks for that!

Best regards,

tomthun aka. Thomas Heinzinger ;)

**Comment by chhh** [comment] 2018-03-20 17:07
Resolved in v5.2

**Closed by chhh** 2018-03-20 17:07 UTC
Labels: bug
